name: Postagens Automáticas

on:
  push:
    branches:
      - main

jobs:
  postagens:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checar o repositório
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Rodar script de postagens
      run: |
        python postagens_automáticas.py
