name: Automate Postings

on:
  schedule:
    - cron: '0 0 * * *'  # Executa todos os dias à meia-noite (UTC)
  workflow_dispatch:  # Para rodar manualmente, se necessário

jobs:
  postagens:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Instalar dependências do projeto

      - name: Run Postagens Automáticas Script
        run: |
          python postagens_automaticas.py  # Certifique-se de que este seja o nome correto do seu script
